### ISSUE TITLE
Support repos that are outside of GOPATH

### ISSUE THREAD

**Issue by jeromefroe** [digitalocean/gta#15]
Hi! 👋 Just wanted to start by saying this project is awesome and to thank you for open sourcing it! One thing I noticed is that `gta` doesn't seem to support repositories that are outside of one's `GOPATH`. I have a minimal example to demonstrate the issue:

```bash
git clone git@github.com:prometheus/client_golang.git
cd client_golang/
git checkout -b testing
touch api/d
git add api/d
git commit -m "add api/d"
gta
```

If run from within one's `GOPATH`, `gta` will output "github.com/prometheus/client_golang/api", as expected. However, if run from outside one's `GOPATH`, then the output will be empty.

I think the issue stems from [the use of the `ImportDir` method from the `go/build` package](https://github.com/digitalocean/gta/blob/master/packager.go#L105). `ImportDir` just calls `Import`, which has support for detecting if a package uses go modules via the [`importGo` method](https://golang.org/src/go/build/build.go?s=15602:15679#L1006). Unfortunately, the `Import` method [will only use that method if the path that is passed to it is not local](https://golang.org/src/go/build/build.go?s=15602:15679#L544) but [`ImportDir` always passes a path of "." to `Import`](https://golang.org/src/go/build/build.go?s=15602:15679#L446).

**Comment by bhcleek** [comment]
Support for modules was added before gta was open sourced. I thought we handled all of the paths that were reported as `.`. I'll take a closer look soon to see if I can identify the problem and the right solution.

**Comment by bhcleek** [comment]
@jeromefroe gta is doing the right thing (there is code in `packager.go` that resolve paths when `go/build` them to `.`). I suspect the problem that you're running into is not having an `include` value.  Without an `-include` value, only the package in the current working directory will be resolvable.

Can you try `gta -include github.com/prometheus/client_golang`?

Also be sure that your working directory is not within a symlink path.

**Comment by jeromefroe** [comment]
@bhcleek you're exactly right! I had tried `gta -include $(go list ./...)` initially, but the root of the repo I was using doesn't include any Go code, just our `go.mod` file, and so it wasn't in the output of `go list ./...`. Setting the `include` flag to be the the root of the repo though gave me the output I expected. I also made the mistake when I used `github.com/prometheus/client_golang` to create a reproducible example of doing everything within my `/tmp` directory which is a symlink 🤦 .

Thanks for the help! Really excited to begin using this tool!

**Comment by bhcleek** [comment]
@jeromefroe I'm happy to help. I may try to resolve the symlink issue soon; I _think_ it's a relatively simple problem to solve.

When you're in a module, you could use `gta -include "$(go list all)"` to list all of the packages, but you probably don't want to do that if you have any vendored code; `gta -include "$(go list -m)"` is probably the preferred incantation.

Thank your for a clear a clearly reproducible bug report. I appreciated the explicit steps in the code block and the clear description of the problem you were seeing.
