### ISSUE TITLE
can't list dirty packages: folder/backend/pkg/helper not found.

### ISSUE THREAD

**Issue by irahulranjan** [digitalocean/gta#23]
Hi, I have the following project structure
```
    - test-project/
      - backend/
         - cmd/
         - pkg/
         - go.mod
```

The go module name is github.com/username/test-project. When I try GTA I get the following error:
```
  can't list dirty packages: test-project/backend/pkg/helper not found.
```

**Comment by bhcleek** [comment]
In module aware mode, your working directory needs to be within the module. e.g. `gta` should be run in your `test-project/backend` directory.

**Comment by irahulranjan** [comment]
Hi @bhcleek, I am running it inside project/backend (mod file location).

**Comment by bhcleek** [comment]
Do you have an import statement for `test-project/backend/pkg/helper` that should be `github.com/username/test-project/backend/pkg/helper`?

**Comment by irahulranjan** [comment]
I have imported as you have suggested.

**Comment by bhcleek** [comment]
@irahulranjan can you provide a repository and branch that exhibits the problem you've described?

**Comment by bhcleek** [comment]
closing for lack of feedback
