### ISSUE TITLE
gta -base origin/master -include $(go list ./...) is bad example for some reason

### ISSUE THREAD

**Issue by tristoney** [digitalocean/gta#37]
## Background
I'm recently doing repo migration to a new mono-repo, which has *no go file in its root directory*. I follow the example https://github.com/digitalocean/gta/blob/master/README.md#usage , and gta do not work as I expect.

## Reason
before
```bash


➜  foo git:(master) tree         
.
├── bar
│   └── a.go
├── go.mod
├── go.sum
└── zoo
    └── b.go

```
after
```bash
.
├── bar
│   └── a.go
├── go.mod
├── go.sum
└── zoo
    ├── b.go
    └── c.go

2 directories, 5 files
```

`go list ./...` returns a list of your go packages, start with the root module, e.g. `foo`. But if you don't have any go file in root directory( if the doc.go doesn't exist), it starts with the first sub package in alphabet order, e.g. `foo/bar`. So if you change foo/hi package,  `gta -base origin/master -include $(go list ./...)` will give you an empty result nor `foo/zoo`.

**Comment by bhcleek** [comment]
`go list` will return the import path of each package. In your example, it would return `foo/bar` and `foo/bar/hi` when `foo` has a `go.mod` and a go file in each `bar` and `bar/hi`, and in a case where `bar` does not contain a go file, it would return `foo/bar/hi`.

**Comment by tristoney** [comment]
> `go list` will return the import path of each package. In your example, it would return `foo/bar` and `foo/bar/hi` when `foo` has a `go.mod` and a go file in each `bar` and `bar/hi`, and in a case where `bar` does not contain a go file, it would return `foo/bar/hi`.

Sorry, let me explain about this example. The `include` param of the command is a comma separated string, but the result of `go list ./…` is a list separated by '\n'. So the example equals to `gta -include foo` when there is no go file in `foo` directory, but `foo/bar` changes.

**Comment by bhcleek** [comment]
Oh, I see. Yes, we should fix the readme. In the meantime, you use pass the module as the argument to `include` (e.g. `gta -base master -include github.com/tristoney/foo/`
